
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqfnokbhdzmffywksmvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxZm5va2JoZHptZmZ5d2tzbXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTQ5OTEsImV4cCI6MjA2MTQzMDk5MX0.zEcmgS5QoeQlOQlXVsdIC3IXjWXfFvLacK4f3wIROBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
